import * as vscode from 'vscode';
import { promisify } from 'util';
import { Worker } from 'worker_threads';
import * as fs from 'fs';

import { SignalId, NetlistId, VaporviewDocumentDelegate} from './viewer_provider';
// Import the code generated by wit2ts
// If this file is not present, run `npm run generate:model` to generate it
// See GETTING_STARTED.md for more details
import { filehandler } from './filehandler';

const moduleIcon = new vscode.ThemeIcon('chip',             new vscode.ThemeColor('charts.purple'));
const funcIcon   = new vscode.ThemeIcon('symbol-module',    new vscode.ThemeColor('charts.yellow'));
const scopeIcon  = new vscode.ThemeIcon('symbol-module',    new vscode.ThemeColor('charts.white'));
const regIcon    = new vscode.ThemeIcon('symbol-array',     new vscode.ThemeColor('charts.green'));
const wireIcon   = new vscode.ThemeIcon('symbol-interface', new vscode.ThemeColor('charts.pink'));
const intIcon    = new vscode.ThemeIcon('symbol-variable',  new vscode.ThemeColor('charts.blue'));
const paramIcon  = new vscode.ThemeIcon('settings',         new vscode.ThemeColor('charts.orange'));
const realIcon   = new vscode.ThemeIcon('symbol-constant',  new vscode.ThemeColor('charts.purple'));

export type NetlistIdTable = NetlistIdRef[];
export type NetlistIdRef = {
  netlistItem: NetlistItem;
  displayedItem: NetlistItem | undefined;
  signalId: SignalId;
};
type WaveformTopMetadata = {
  fileSize:    number;
  fd:          number;
  timeTableLoaded: boolean;
  moduleCount: number;
  netlistIdCount: number;
  signalIdCount: number;
  timeEnd:     number;
  chunkTime:   number;
  chunkCount:  number;
  timeScale:   number;
  defaultZoom: number;
  timeUnit:    string;
};

export function createScope(name: string, type: string, path: string, netlistId: number) {

  const typename = type.toLocaleLowerCase();
  let icon = scopeIcon;
  if      (typename === 'module' ) {icon = moduleIcon;} 
  else if (typename === 'function') {icon = funcIcon;}

  const module    = new NetlistItem(name, 'module', 0, 0, netlistId, name, path, 0, 0, [], vscode.TreeItemCollapsibleState.Collapsed);
  module.iconPath = icon;

  return module;
}
  
function bitRangeString(msb: number, lsb: number): string {
  if (msb < 0 || lsb < 0) {return "";}
  if (msb === lsb) {return " [" + msb + "]";}
  return " [" + msb + ":" + lsb + "]";
}
  
export function createVar(name: string, type: string, path: string, netlistId: NetlistId, signalId: SignalId, width: number, msb: number, lsb: number) {
  const field = bitRangeString(msb, lsb);
  const variable = new NetlistItem(name + field, type, width, signalId, netlistId, name, path, msb, lsb, [], vscode.TreeItemCollapsibleState.None, vscode.TreeItemCheckboxState.Unchecked);
  const typename = type.toLocaleLowerCase();
  if ((typename === 'wire') || (typename === 'reg')) {
    if (width > 1) {variable.iconPath = regIcon;}
    else           {variable.iconPath = wireIcon;}
  }
  else if (typename === 'integer')   {variable.iconPath = intIcon;}
  else if (typename === 'parameter') {variable.iconPath = paramIcon;}
  else if (typename === 'real')      {variable.iconPath = realIcon;}

  return variable;
}

// #region VaporviewDocument
export class VaporviewDocument extends vscode.Disposable implements vscode.CustomDocument {

  private open  = promisify(fs.open);
  private close = promisify(fs.close);

  private readonly _uri: vscode.Uri;
  // Hierarchy
  public treeData:         NetlistItem[] = [];
  public displayedSignals: NetlistItem[] = [];
  private _netlistIdTable: NetlistIdTable = [];
  // Wasm
  private readonly _delegate: VaporviewDocumentDelegate;
  public _wasmWorker: Worker;
  public wasmApi: any;
  private fileBuffer: Uint8Array;
  // Webview
  public webviewPanel: vscode.WebviewPanel | undefined = undefined;
  private _webviewInitialized: boolean = false;
  public metadata:   WaveformTopMetadata = {
    fileSize:    0,
    fd:          0,
    timeTableLoaded: false,
    moduleCount:    0,
    netlistIdCount: 0,
    signalIdCount:  0,
    timeEnd:     0,
    chunkTime:   128,
    chunkCount:  0,
    timeScale:   1,
    defaultZoom: 1,
    timeUnit:    "ns",
  };
  public webviewContext = {
    markerTime: null,
    altMarkerTime: null,
    selectedSignal: null,
    displayedSignals: [],
    zoomRatio: 1,
    scrollLeft: 0,
    numberFormat: 16,
  };

  static async create(
    uri: vscode.Uri,
    backupId: string | undefined,
    wasmWorker: Worker,
    wasmModule: WebAssembly.Module,
    delegate: VaporviewDocumentDelegate,
  ): Promise<VaporviewDocument | PromiseLike<VaporviewDocument>> {

    const document = new VaporviewDocument(uri, wasmWorker, delegate);
    await document.createWasmApi(wasmModule);
    document.load();
    return document;
  }

  private constructor(
    uri: vscode.Uri,
    _wasmWorker: Worker,
    delegate: VaporviewDocumentDelegate,
  ) {
    super(() => this.dispose());
    this._uri        = uri;
    this._wasmWorker = _wasmWorker;
    this._delegate   = delegate;
    this.fileBuffer  = new Uint8Array(65536);
  }

  private async load() {
    const stats                = fs.statSync(this.uri.fsPath);
    const fileType             = this.uri.fsPath.split('.').pop()?.toLocaleLowerCase();
    this.metadata.fd           = await this.open(this.uri.fsPath, 'r');
    this.metadata.fileSize     = stats.size;
    const fstMaxStaticLoadSize = vscode.workspace.getConfiguration('vaporview').get('fstMaxStaticLoadSize');
    const maxStaticSize        = Number(fstMaxStaticLoadSize) * 1048576;
    const loadStatic           = (stats.size < maxStaticSize);
    let bufferSize             = 60 * 1024; // WASM is limited to 64KB, and we need some extra space for the function call overhead

    // For VCD files, we stream the file, so we want to use a larger buffer size
    // For FST files, we want to use Rust's default buffer size of 8192 bytes,
    // but we don't care about buffer size if we statically load the file
    if (fileType === 'fst' && loadStatic === false) {
      bufferSize = 8192;
      vscode.window.showInformationMessage(
        this.uri.fsPath + ' is larger than the max static load size of ' + fstMaxStaticLoadSize +
        ' MB. File will be loaded dynamically. You can configure the max load size in your extension settings.');
    }

    await vscode.window.withProgress({
      location: vscode.ProgressLocation.Notification,
      title: "Parsing Netlist for " + this.uri.fsPath,
      cancellable: false
    }, async () => {
      await this.wasmApi.loadfile(BigInt(stats.size), this.metadata.fd, loadStatic, bufferSize);
    });

    this._delegate.updateViews(this.uri);
    await this._readBody();
  }

  public readonly service: filehandler.Imports.Promisified = {

    log: (msg: string) => {console.log(msg);},
    fsread: (fd: number, offset: bigint, length: number): Uint8Array => {

      const bytesRead = fs.readSync(fd, this.fileBuffer, 0, length, Number(offset));
      return this.fileBuffer.subarray(0, bytesRead);
    },
    getsize: (fd: number): bigint => {
      const stats = fs.fstatSync(fd);
      return BigInt(stats.size);
    },
    setscopetop: (name: string, id: number, tpe: string) => {

      const scope = createScope(name, tpe, "", id);
      this.treeData.push(scope);
      this._netlistIdTable[id] = {netlistItem: scope, displayedItem: undefined, signalId: 0};
    },
    setmetadata: (scopecount: number, varcount: number, timescale: number, timeunit: string) => {
      this.metadata.moduleCount = scopecount;
      this.metadata.netlistIdCount = varcount;
      this.metadata.timeScale = timescale;
      this.metadata.timeUnit = timeunit;
      this._netlistIdTable = new Array(varcount);
    },
    setchunksize: (chunksize: bigint, timeend: bigint) => {
      this.setChunkSize(Number(chunksize));
      this.metadata.timeEnd = Number(timeend);
      this.metadata.chunkCount = Math.ceil(this.metadata.timeEnd / this.metadata.chunkTime);
      this.metadata.timeTableLoaded = true;
      this.onDoneParsingWaveforms();
    },
    sendtransitiondatachunk: (signalid: number, totalchunks: number, chunknum: number, transitionData: string) => {

      this.webviewPanel?.webview.postMessage({
        command: 'update-waveform-chunk',
        signalId: signalid,
        transitionDataChunk: transitionData,
        totalChunks: totalchunks,
        chunkNum: chunknum
      });
    }
  };
  // The implementation of the log function that is called from WASM

  public get uri() { return this._uri; }
  public get netlistIdTable(): NetlistIdTable { return this._netlistIdTable; }
  public get webviewInitialized(): boolean { return this._webviewInitialized; }

  public async createWasmApi(wasmModule: WebAssembly.Module) {
    this.wasmApi = await filehandler._.bind(this.service, wasmModule, this._wasmWorker);
  }

  private _readBody() {
    vscode.window.withProgress({
      location: vscode.ProgressLocation.Notification,
      title: "Parsing Waveforms for " + this.uri.fsPath,
      cancellable: false
    }, async (progress) => {
      await this.wasmApi.readbody();
    });
  }

  public onWebviewReady(webviewPanel: vscode.WebviewPanel) {
    console.log("Webview Ready");
    this.webviewPanel = webviewPanel;
    if (this._webviewInitialized) {return;}
    if (!this.metadata.timeTableLoaded) {return;}
    //console.log("creating ruler");
    webviewPanel.webview.postMessage({
      command: 'create-ruler',
      waveformDataSet: this.metadata,
    });
    //console.log(this.metadata);
    this._webviewInitialized = true;
  }

  public onDoneParsingWaveforms() {
    console.log("onDoneParsingWaveforms");
    if (this.webviewPanel) {
      this.onWebviewReady(this.webviewPanel);
    }
    //this.close(this.metadata.fd);
  }

  public setNetlistIdTable(netlistId: NetlistId, displayedSignalViewRef: NetlistItem | undefined) {
    const viewRef = this._netlistIdTable[netlistId];
    if (viewRef === undefined) {return;}
    viewRef.displayedItem = displayedSignalViewRef;
    this._netlistIdTable[netlistId] = viewRef;
  }

  public setChunkSize(minTimeStemp: number) {
    // Prevent weird zoom ratios causing strange floating point math errors
    const newMinTimeStemp     = 10 ** (Math.round(Math.log10(minTimeStemp / 128)) | 0);
    const chunkTime           = newMinTimeStemp * 128;
    this.metadata.chunkTime   = chunkTime;
    this.metadata.defaultZoom = 512 / chunkTime;
  }

  public getSettings() {
    return {
      extensionVersion: vscode.extensions.getExtension('Lramseyer.vaporview')?.packageJSON.version,
      fileName: this.uri.fsPath,
      markerTime: this.webviewContext.markerTime,
      altMarkerTime: this.webviewContext.altMarkerTime,
      selectedSignal: this.getNameFromNetlistId(this.webviewContext.selectedSignal),
      zoomRatio: this.webviewContext.zoomRatio,
      scrollLeft: this.webviewContext.scrollLeft,
      displayedSignals: this.webviewContext.displayedSignals.map((n: NetlistId) => {return this.getNameFromNetlistId(n);}),
    };
  }

  public formatTime(time: number) {
    const timeValue = time * this.metadata.timeScale;
    return timeValue.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + ' ' + this.metadata.timeUnit;
  }

  public async findTreeItem(modulePath: string, msb: number | undefined, lsb: number | undefined): Promise<NetlistItem | null> {
    const module = this.treeData.find((element) => element.label === modulePath.split('.')[0]);
    if (!module) {return null;}
    return await module.findChild(modulePath.split('.').slice(1).join('.'), this, msb, lsb);
  }

  public getNameFromNetlistId(netlistId: NetlistId | null) {
    if (netlistId === null) {return null;}
    const netlistData  = this.netlistIdTable[netlistId]?.netlistItem;
    const modulePath   = netlistData?.modulePath;
    const signalName   = netlistData?.name;
    const numberFormat = netlistData?.numberFormat;
    const msb          = netlistData?.msb;
    const lsb          = netlistData?.lsb;
    return {
      name: modulePath + '.' + signalName,
      numberFormat: numberFormat,
      msb: msb,
      lsb: lsb,
    };
  }

  public async renderSignals(netlistIdList: NetlistId[]) {
    // Render the signal with the provided ID
    //console.log('renderSignals()');

    const signalList: any = [];
    if (!this.webviewPanel) {return;}

    netlistIdList.forEach((netlistId) => {
      const metadata  = this.netlistIdTable[netlistId]?.netlistItem;
      if (!metadata) {return;}

      signalList.push({
        netlistId:  metadata.netlistId,
        signalId:   metadata.signalId,
        signalWidth: metadata.width,
        signalName: metadata.name,
        modulePath: metadata.modulePath,
        numberFormat: metadata.numberFormat
     });
    });
    this.webviewPanel.webview.postMessage({
      command: 'add-variable',
      signalList: signalList
    });
  }

  public removeSignalFromWebview(netlistId: NetlistId) {
    // Render the signal with the provided ID
    if (!this.webviewPanel) {return;}

    this.webviewPanel.webview.postMessage({ 
      command: 'remove-signal',
      netlistId: netlistId
   });
  }

  async getChildrenExternal(element: NetlistItem | undefined) {

    if (!element) {return Promise.resolve(this.treeData);} // Return the top-level netlist items
    if (!this.wasmApi) {return Promise.resolve([]);}
    if (element.children.length > 0) {return Promise.resolve(element.children);}

    let modulePath = "";
    if (element.modulePath !== "") {modulePath += element.modulePath + ".";}
    modulePath += element.name;
    let itemsRemaining = Infinity;
    let startIndex     = 0;
    const result: NetlistItem[] = [];

    //console.log(element);
    let callLimit = 255;
    const varTable: any = {};
    while (itemsRemaining > 0) {
      //console.log("calling getscopes for " + modulePath + " with start index " + startIndex);
      const children = await this.wasmApi.getchildren(element.netlistId, startIndex);
      const childItems = JSON.parse(children);
      //console.log(children);
      //console.log(childItems);
      itemsRemaining = childItems.remainingItems;
      startIndex    += childItems.totalReturned;

      childItems.scopes.forEach((child: any) => {
        result.push(createScope(child.name, child.type, modulePath, child.id));
      });
      childItems.vars.forEach((child: any) => {
        // Need to handle the case where we get a variable with the same name but
        // different bit ranges.
        const varItem = createVar(child.name, child.type, modulePath, child.netlistId, child.signalId, child.width, child.msb, child.lsb);
        if (varTable[child.name] === undefined) {
          varTable[child.name] = [varItem];
        } else {
          varTable[child.name].push(varItem);
        }
        this.netlistIdTable[child.netlistId] = {netlistItem: varItem, displayedItem: undefined, signalId: child.signalId};
      });

      callLimit--;
      if (callLimit <= 0) {break;}
    }

    for (const [key, value] of Object.entries(varTable)) {
      if ((value as NetlistItem[]).length === 1) {
        result.push((value as NetlistItem[])[0]);
      } else {
        const varList = value as NetlistItem[];
        const bitList: NetlistItem[] = [];
        const busList: NetlistItem[] = [];
        let maxWidth = 0;
        let parent: any = undefined; // set to any because the linter is complaining
        varList.forEach((varItem) => {
          if (varItem.width === 1) {bitList.push(varItem);}
          else {busList.push(varItem);}
        });
        busList.forEach((busItem: NetlistItem) => {
          if (busItem.width > maxWidth) {
            maxWidth = busItem.width;
            parent = busItem;
          }
          result.push(busItem);
        });
        if (parent !== undefined) {
          parent.children = bitList;
          //parent.collapsibleState = vscode.TreeItemCollapsibleState.Collapsed;
        } else {
          result.push(...bitList);
        }

      }
    }

    element.children = result;
    return Promise.resolve(element.children);
  }

  public async unload() {
    console.log("Reloading document");
    this.treeData         = [];
    this.displayedSignals = [];
    this._netlistIdTable  = [];
    this.close(this.metadata.fd);
    await this.wasmApi.unload();
    this.metadata.timeTableLoaded = false;
    this.webviewPanel?.webview.postMessage({command: 'unload'});
    this._webviewInitialized = false;
  }

  public async reload() {
    await this.unload();
    await this.load();
  }

  //private readonly _onDidDispose = this._register(new vscode.EventEmitter<void>());
  /**
   * Fired when the document is disposed of.
   */
  //public readonly onDidDispose = this._onDidDispose.event;

  /**
   * Called by VS Code when there are no more references to the document.
   * This happens when all editors for it have been closed.
   */
  dispose(): void {
    this.unload();
    this._wasmWorker.terminate();
    this._delegate.updateViews(this.uri);
    //this._onDidDispose.fire();
  }
}

// #region WebviewCollection
/**
 * Tracks all webviews.
 */
export class WebviewCollection {

  private numWebviews = 0;
  public get getNumWebviews() {return this.numWebviews;}

  private readonly _webviews = new Set<{
    readonly resource: string;
    readonly webviewPanel: vscode.WebviewPanel;
  }>();

  /**
   * Get all known webviews for a given uri.
   */
  public *get(uri: vscode.Uri): Iterable<vscode.WebviewPanel> {
    const key = uri.toString();
    for (const entry of this._webviews) {
      if (entry.resource === key) {
        yield entry.webviewPanel;
      }
    }
  }

  /**
   * Add a new webview to the collection.
   */
  public add(uri: vscode.Uri, webviewPanel: vscode.WebviewPanel) {
    const entry = { resource: uri.toString(), webviewPanel };
    this._webviews.add(entry);
    this.numWebviews++;

    webviewPanel.onDidDispose(() => {
      this._webviews.delete(entry);
      this.numWebviews--;
    });
  }
}

// #region NetlistTreeDataProvider
export class NetlistTreeDataProvider implements vscode.TreeDataProvider<NetlistItem> {

  private treeData: NetlistItem[] = [];
  private _onDidChangeTreeData: vscode.EventEmitter<NetlistItem | undefined> = new vscode.EventEmitter<NetlistItem | undefined>();
  readonly onDidChangeTreeData: vscode.Event<NetlistItem | undefined> = this._onDidChangeTreeData.event;
  private document: VaporviewDocument | undefined;

  public setCheckboxState(netlistItem: NetlistItem, checkboxState: vscode.TreeItemCheckboxState) {
    netlistItem.checkboxState = checkboxState;
    this._onDidChangeTreeData.fire(undefined); // Trigger a refresh of the Netlist view
  }

  public loadDocument(document: VaporviewDocument) {
    this.setTreeData(document.treeData);
    this.document = document;
  }

  // Method to set the tree data
  public setTreeData(netlistItems: NetlistItem[]) {
    this.treeData = netlistItems;
    this._onDidChangeTreeData.fire(undefined); // Trigger a refresh of the Netlist view
  }

  public hide() {
    this.setTreeData([]);
    this.document = undefined;
  }

  public getTreeData(): NetlistItem[] {return this.treeData;}
  getTreeItem(element:  NetlistItem): vscode.TreeItem {return element;}
  getChildren(element?: NetlistItem): Thenable<NetlistItem[]> {
    return this.document?.getChildrenExternal(element) ?? Promise.resolve([]);
  }

  getParent(element: NetlistItem): vscode.ProviderResult<NetlistItem> {
    if (this.document) {
      return element.findChild(element.modulePath, this.document, undefined, undefined);
    }
    return null;
  }

  refresh(): void {
    this._onDidChangeTreeData.fire(undefined);
  }

}

export class DisplayedSignalsViewProvider implements vscode.TreeDataProvider<NetlistItem> {
  private treeData: NetlistItem[] = [];
  private _onDidChangeTreeData: vscode.EventEmitter<NetlistItem | undefined> = new vscode.EventEmitter<NetlistItem | undefined>();
  readonly onDidChangeTreeData: vscode.Event<NetlistItem | undefined> = this._onDidChangeTreeData.event;

  // Method to set the tree data
  public setTreeData(netlistItems: NetlistItem[]) {
    this.treeData = netlistItems;
    this._onDidChangeTreeData.fire(undefined); // Trigger a refresh of the Netlist view
  }

  public hide() {
    this.setTreeData([]);
  }

  public getTreeData(): NetlistItem[] {return this.treeData;}

  getTreeItem(element:  NetlistItem): vscode.TreeItem {return element;}
  getChildren(element?: NetlistItem): Thenable<NetlistItem[]> {
    if (element) {return Promise.resolve(element.children);} // Return the children of the selected element
    else         {return Promise.resolve(this.treeData);} // Return the top-level netlist items
  }

  public addSignalToTreeData(netlistItem: NetlistItem): NetlistItem {
    const n = netlistItem;
    const displayedItem = new NetlistItem(n.label, n.type, n.width, n.signalId, n.netlistId, n.name, n.modulePath, n.msb, n.lsb, n.children, vscode.TreeItemCollapsibleState.None, n.checkboxState);
    displayedItem.iconPath = n.iconPath;
    this.treeData.push(displayedItem);
    this._onDidChangeTreeData.fire(undefined); // Trigger a refresh of the Netlist view
    return displayedItem;
  }

  public removeSignalFromTreeData(netlistItem: NetlistItem) {
    const index = this.treeData.indexOf(netlistItem);
    if (index > -1) {
      this.treeData.splice(index, 1);
    }
    this._onDidChangeTreeData.fire(undefined); // Trigger a refresh of the Netlist view
  }

  public getParent(element: NetlistItem): vscode.ProviderResult<NetlistItem> {
    return null;
  }

  refresh(): void {
    this._onDidChangeTreeData.fire(undefined);
  }
}

interface TreeCheckboxChangeEvent<T> {
  item: T;
  checked: boolean;
}

// #region NetlistItem
export class NetlistItem extends vscode.TreeItem {
  private _onDidChangeCheckboxState: vscode.EventEmitter<vscode.TreeItem | undefined | null> = new vscode.EventEmitter<vscode.TreeItem | undefined | null>();
  onDidChangeCheckboxState: vscode.Event<vscode.TreeItem | undefined | null> = this._onDidChangeCheckboxState.event;

  public numberFormat: number;

  constructor(
    public readonly label:      string,
    public readonly type:       string,
    public readonly width:      number,
    public readonly signalId:   SignalId, // Signal-specific information
    public readonly netlistId:  NetlistId, // Netlist-specific information
    public readonly name:       string,
    public readonly modulePath: string,
    public readonly msb:        number,
    public readonly lsb:        number,
    public children:         NetlistItem[] = [],
    public collapsibleState: vscode.TreeItemCollapsibleState,
    public checkboxState:    vscode.TreeItemCheckboxState | undefined = undefined // Display preference
  ) {
    super(label, collapsibleState);
    this.numberFormat = 16;
    if (collapsibleState === vscode.TreeItemCollapsibleState.None) {
      this.contextValue = 'netlistVar'; // Set a context value for leaf nodes
    } else {
      this.contextValue = 'netlistScope'; // Set a context value for parent nodes
    }
  }

  // Method to recursively find a child element in the tree
  async findChild(label: string, document: VaporviewDocument, msb: number | undefined, lsb: number | undefined): Promise<NetlistItem | null> {

    // If the label is empty, return the current item, but try to find the child with the specified msb and lsb
    if (label === '') {
      if (this.children.length === 0 || this.children === undefined) {return this;}
      if (msb === undefined || lsb === undefined) {return this;}
      if (this.msb === msb && this.lsb === lsb) {return this;}

      const returnItem = this.children.find(childItem => childItem.msb === msb && childItem.lsb === lsb);
      if (returnItem) {return returnItem;}
      return this;
    }

    const subModules    = label.split(".");
    const currentModule = subModules.shift();
    if (this.children.length === 0) {
      await document.getChildrenExternal(this);
    }

    const childItem     = this.children.find((child) => child.name === currentModule);

    if (childItem) {
      return await childItem.findChild(subModules.join("."), document, msb, lsb);
    } else {
      return null;
    }
  }

  handleCommand() {
    //console.log("handleCommand()");
    //console.log(this);
  }

  // Method to toggle the checkbox state
  toggleCheckboxState() {
    this.checkboxState = this.checkboxState === vscode.TreeItemCheckboxState.Checked
      ? vscode.TreeItemCheckboxState.Unchecked
      : vscode.TreeItemCheckboxState.Checked;
    this._onDidChangeCheckboxState.fire(this);
  }
}